# Generated by Django 4.1.5 on 2023-02-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manyToOne', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporter',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='apellido',
            new_name='last_name',
        ),
    ]
