# Generated by Django 4.1.5 on 2023-02-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='signature',
            field=models.CharField(default='legacySignature', max_length=127),
        ),
    ]
