# Generated by Django 4.1.5 on 2023-02-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_alter_comments_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
